package sample

import (
	"errors"
	"fmt"
	"serialize/decoders"
	"serialize/encoders"
)

// THIS FILE WAS GENERATED BY serialize
// PLEASE DO NOT EDIT

func (self Foo) Serialize() ([]byte, error) {
	var output, bytesTemp []byte

	bytesTemp = encoders.IntAsBytes(self.Bar)
	output = append(output, bytesTemp...)

	bytesTemp = encoders.UintAsBytes(self.Fizz)
	output = append(output, bytesTemp...)

	bytesTemp = encoders.StringAsBytes(self.Buzz)
	output = append(output, bytesTemp...)

	bytesTemp = encoders.BoolAsBytes(self.FizzBuzz)
	output = append(output, bytesTemp...)
	return output, nil
}
func (self Foo) Unserialize(data []byte) (interface{}, error) {
	var output Foo
	var index uint64 = 0
	var consumed uint64 = 0
	var err error

	output.Bar, consumed, err = decoders.IntFromBytes(data[index:])
	if err != nil {
		return output, errors.New(fmt.Sprintf("Could not decode at %d: %s\n", index, err.Error()))
	}
	index += consumed

	output.Fizz, consumed, err = decoders.UintFromBytes(data[index:])
	if err != nil {
		return output, errors.New(fmt.Sprintf("Could not decode at %d: %s\n", index, err.Error()))
	}
	index += consumed

	output.Buzz, consumed, err = decoders.StringFromBytes(data[index:])
	if err != nil {
		return output, errors.New(fmt.Sprintf("Could not decode at %d: %s\n", index, err.Error()))
	}
	index += consumed

	output.FizzBuzz, consumed, err = decoders.BoolFromBytes(data[index:])
	if err != nil {
		return output, errors.New(fmt.Sprintf("Could not decode at %d: %s\n", index, err.Error()))
	}
	index += consumed
	return output, nil
}
